### ISSUE TITLE
Documentation is inaccurate.

### ISSUE THREAD

**Issue by Hemston** [woodyrew/php-RestMe#1]
Hey Woodstock!

The naming convention for endpoints outlined in the documentation (endpoint/endpoint.inc.php) does not correlate with what RestMe seems to expect (endpoint/Endpoint.php).

Similarly, the documentation implies that accessing the resource api/endpoint will just work however my experience was that this resulted in a 404 as the real file is api/endpoint.php. What additional configuration needs to be carried out to facilitate the use of clean URLs? Is it some htaccess rewrite rule wizardry?

**Comment by woodyrew** [comment]
It's not rewrite wizardry but I believe you do need `MultiViews` and (I think) `options indexes` enabled for the **api** directory.

**Comment by woodyrew** [comment]
Closed with PR #2
